=== Myrninvollo/freerails/src/jfreerails/data/terrain_tiles.dtd
<!--
    Typical usage:

    <?xml version="1.0"?>

    <!DOCTYPE Tiles SYSTEM "tiles_Tiles.dtd">

    <Tiles>
    ...
    </Tiles>
-->
<!-- specials are tile types that, in a sense, extend another type.  E.g. habour is a special of ocean.-->

  <!ELEMENT specials (Tile)*>

  <!ELEMENT Type EMPTY>
  <!ATTLIST Type
    rgb CDATA #IMPLIED
  >

  
  <!ELEMENT Tile (specials|treatTheseAsTheSameType)*>
  <!ATTLIST Tile
    tileSelector (Standard | Chequered | RiverStyle | special | ForestStyle ) #REQUIRED
    Type CDATA #REQUIRED
    rgb CDATA #REQUIRED
    Y CDATA #REQUIRED
    X CDATA #REQUIRED
  >
  
  <!-- Some tile types need to be treated the same as others when the map is drawn.  E.g. rivers flow into the ocean, so 
  river tiles need to treat ocean tiles as the same type-->
  <!ELEMENT treatTheseAsTheSameType (Type)*>

  <!ELEMENT Tile_set (Tile)*>
  <!ATTLIST Tile_set
    Width CDATA #REQUIRED
    Class CDATA #IMPLIED
    Y CDATA #REQUIRED
    Height CDATA #REQUIRED
    X CDATA #REQUIRED
  >

  <!ELEMENT Tiles (Tile_set)*>

=== Myrninvollo/freerails/src/jfreerails/data/terrain_tiles.xml
<!DOCTYPE Tiles SYSTEM "terrain_tiles.dtd">

<!---->

<Tiles>
	<Tile_set X="0" Y="0" Height="30" Width="30" Class="Terrain">
		<Tile Type="slums" Category="Urban" X="2" Y="8" rgb="0" tileSelector="Chequered"/>
		<Tile Type="Resource" Category="Special" X="8" Y="8" rgb="ef901d" tileSelector="Standard"/>
		<Tile Type="Village" Category="Urban" X="0" Y="8" rgb="d86c48" tileSelector="Chequered"/>
		<Tile Type="Clear" Category="Country" X="0" Y="0" rgb="00b400" tileSelector="RiverStyle"/>
		<Tile Type="Farm" Category="Special" X="0" Y="7" rgb="48fc48" tileSelector="Chequered"/>
		<Tile Type="Desert" Category="Country" X="0" Y="1" rgb="b42400" tileSelector="RiverStyle"/>
		<Tile Type="City" Category="Urban" X="2" Y="7" rgb="fcfc48" tileSelector="Chequered"/>
		<Tile Type="Ocean" Category="Water" X="0" Y="5" rgb="0000b4" tileSelector="RiverStyle">
			<specials>
				<Tile Type="Harbour" Category="Water" X="12" Y="7" rgb="1eead2" tileSelector="special"/>
			</specials>
		</Tile>
		<Tile Type="River" Category="Water" X="0" Y="4" rgb="0048d8" tileSelector="RiverStyle">
			<treatTheseAsTheSameType>
				<Type rgb="0000b4"/>
				<Type rgb="1eead2"/>
			</treatTheseAsTheSameType>
		</Tile>
		<Tile Type="Resource" Category="Special" X="10" Y="8" rgb="ef901c" tileSelector="Standard"/>
		<Tile Type="Terminal" Category="Special" X="4" Y="7" rgb="4" tileSelector="Standard"/>
		<Tile Type="Jungle" Category="Country" X="0" Y="3" rgb="4890fc" tileSelector="RiverStyle"/>
		<Tile Type="Hills" Category="Country" X="0" Y="6" rgb="b4b4b4" tileSelector="ForestStyle"/>
		<Tile Type="Foothills" Category="Country" X="0" Y="6" rgb="90d8fc" tileSelector="ForestStyle"/>
		<Tile Type="Mountain" Category="Country" X="8" Y="6" rgb="ffffff" tileSelector="ForestStyle"/>
	</Tile_set>
</Tiles>
